### ISSUE TITLE
Block Textures

### ISSUE THREAD

**Issue by polserull** [LabyStudio/java-minecraft#2]
When you try to create a new block and set the texture id to 16 (first texture on second row of terrain.png) it bugs out and assigns a different texture from the first row.

**Comment by LabyStudio** [comment]
I guess you have to change some of the calculation here: https://github.com/LabyStudio/java-minecraft/blob/master/src/main/java/de/labystudio/game/render/world/BlockRenderer.java#L40

You can take a look at this project: https://github.com/LabyStudio/js-minecraft/blob/master/src/js/net/minecraft/client/render/BlockRenderer.js#L231
That should be right

**Comment by polserull** [comment]
Figured it out, its working now thanks for the help ^^
